name: Build
on:
  pull_request:
    paths:
      - '**.bs'
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: bikeshed
          DESTINATION: pr-preview/preview--${{ github.ref }}/index.html
          SOURCE: spec.bs
          GH_PAGES_BRANCH: gh-pages
          BUILD_FAIL_ON: warning
